name: CI
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]      
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.9"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      # Install dependencies       
      - name: Install deps
        shell: bash            
        run: |
          python -m pip install -U pip
          python -m pip install -U build cmake ninja "pybind11>=2.11" "scikit-build-core>=0.10"
      
      # Build and install
      - name: Install wheel
        shell: bash
        run: |
          python -m build --sdist --wheel
          python -m pip install dist/*.whl

     # Smoke test
      - name: Smoke test
        shell: bash
        run: |
          python - <<'PY'
          import rts_smoother, numpy as np
          x = np.random.randn(50, 3)
          y = rts_smoother.smooth(x, 1e-4, 1e-3)
          assert y.shape == x.shape
          print("OK:", y.shape)
          PY

      # Validate
      - name: Validate
        shell: bash      
        run: |
          python -m pip install -U twine
          twine check dist/*
