name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    needs: [build-wheels, build-sdist]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      # Install dependencies 
      - run: python -m pip install -U pip twine

      # Upload
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing dist/**/*
